= BDR Ref

Reference data for the _Biodiversity Data Repository_.

This repository contains reference data - background models, vocabularies, reference spatial and agents data - for the _Biodiversity Data Repository_ which is a database of species observations data being collected by the https://www.dcceew.gov.au[Department of Climate Change, Energy, the Environment and Water (DCCEEW)].

== Contents

* *graphs.ttl*
** records the list of Names Graphs within the BDR that all other content is loaded into
* *agents/*
** Organisations & People
* *background*
** background models (ontologies)
* *vocabularies/*
** BDR system vocabs (not TERN Ont or ABIS vocabs)

== License and Rights

The content of this repository, where generated by DCCEEW is copyrighted as follows:

&copy; Commonwealth of Australia (Department of Climate Change, Energy, the Environment and Water), 2023

This content is available for reuse under the terms of the https://creativecommons.org/licenses/by/4.0/[Creative Commons BY 4.0 license], a copy of the deed of which is stored in the LICENSE file in this repository.

== Contacts

This repository is developed by the BDR team within DCCEEW. Technical lead is:

*Ashley Sommer* +
_Senior Software Engineer_ +
ashley.sommer@csiro.au +
https://orcid.org/0000-0003-0590-0131 +

at the

*Biodiversity Data Repository Team* +
Department of Climate Change, Energy, the Environment and Water +
bdr@dcceew.gov.au +
https://www.dcceew.gov.au

_and_ Data Architect is: 

*Nicholas Car* +
_Data Architect_ +
nick@kurrawong.ai +
https://orcid.org/0000-0002-8742-7730 +

at

*Kurrawong AI* +
bdr@kurrawong.ai +
https://kurrawong.ai

